const text = {
  header: 'Header',
  title: 'Title',
  homeTitle: 'Matches',
  home: 'Home',
  results: 'Results',
  start: 'Start',
  categories: 'Categories',
  correct: 'Correct',
  wrong: 'Wrong',
  agree: 'Agree',
  score: 'Score',
  close: 'Close',
  cancel: 'Cancel',
  timeout: 'Time Out',
  science: 'Science',
  sciences: 'Sciences',
  music: 'Music',
  musics: 'Musics',
  picture: 'Picture',
  pictures: 'Pictures',
  pageNotFound: 'Page not found',
  error: 'error',
  somethingWentWrong: 'Something went wrong',
  setting: 'Setting',
  generalSetting: 'General Setting',
  scoreManualSetting: 'Score Manual Setting',
  clearQuestionArrangement: 'Clear Question Arrangement',
  clearScoreArrangement: 'Clear Score Arrangement',
  restartTheGame: 'Restart the game',
  restartDialog: {
    main: 'Are You Sure Want To Restart the Game?',
    p1: 'If you prees AGREE all Question and Scores Arrangements will delete.',
    p2: 'prees CANCEL to close.',
  },

};

export default text;
